### PR TITLE
(feat) Added React boilerplate.

### LINKED ISSUE #2: (init) Add basic React boilerplate.

### PR DESCRIPTION
**Pull request by ateich**
Closes #2

### CODE REVIEW

**Comment by ateich** [comment]
@adam-back Mind merging this in? I don't have write access :(

**Comment by adamjaffeback** [comment]
Muah ha ha! I control everything!

Yes...

**Comment by adamjaffeback** [comment]
PS, did you catch I made Volta-Charging/Volta-API public?

**Comment by adamjaffeback** [comment]
I made the arbitard group Admin-level. You shouldn't have this issue again.

**Pull request merged**
